AllCops:
  TargetRubyVersion: 2.3
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
