---
template: en/recipe/template.html
tag_type: :xml_comment_like
template_encoding: UTF-8
data: en/recipe/main.aht
data_format: 
data_encoding: UTF-8
output_file: 
blocks:
- label: "#authors"
  data: 
  data_format: 
  data_encoding: 
- label: "#authors|works|name"
  data: en/inner_iteration/data.csv
  data_format: 
  data_encoding: 
---
template: ja/recipe/template.html
tag_type: :xml_comment_like
template_encoding: UTF-8
data: ja/recipe/main.aht
data_format: 
data_encoding: 
output_file: 
blocks:
- label: "#authors"
  data: 
  data_format: 
  data_encoding: 
- label: "#authors|works|name"
  data: ja/inner_iteration/data.csv
  data_format: 
  data_encoding: 
